name: Python Tests

on:
  push:
    branches: [ dev, main, master ]
  pull_request:
    branches: [ dev, main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        python -m pytest tests/test.py -v

    - name: Test basic script functionality
      run: |
        python -c "
        from widget import ReminderWidget
        widget = ReminderWidget('https://example.com/test.json')
        print('✓ Класс ReminderWidget импортирован успешно')
        "